services:
  db:
    image: postgres:15-alpine
    container_name: twitter_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: twitter_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/twitter_db
    volumes:
      - ./static/uploads:/app/static/uploads
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head &&
             python scripts/seed_users.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: